{
 "title": "NetDevice - Interface Detail",
 "description": "Detailed interface stats from prometheus snmp exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus, instance)"
    }
   },
   {
    "name": "ifName",
    "query": {
     "query": "query_result(ifOperStatus{instance=\"$instance\", ifName!~\"Wayne.*\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Connector Present",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifConnectorPresent{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Promiscuous Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifPromiscuousMode{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifName=\"$ifName\"}*1000000 or ifSpeed{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifType_info{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifInOctets{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]))*8",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "(rate(ifHCOutOctets{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifOutOctets{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]))*8",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Broadcast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifInBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifHCOutBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifOutBroadcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifInUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifHCOutUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifOutUcastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifInMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifName}}"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval]) or rate(ifOutMulticastPkts{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifName}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: errors: {{ifName}}"
    },
    {
     "expr": "rate(ifOutErrors{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: errors: {{ifName}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: discards: {{ifName}}"
    },
    {
     "expr": "rate(ifInUnknownProtos{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "IN: unknown protos: {{ifName}}"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$instance\",ifName=\"$ifName\"}[$__rate_interval])",
     "legendFormat": "OUT: discards: {{ifName}}"
    }
   ]
  }
 ]
}